var_minimas = ['AUTORIZACION','ANTIGUEDAD', 'CONTABILIDAD', 'EDAD', 'INGRESOS', 'NO_TRABAJADORES', 'PROPIETARIOS_MUJERES', 'PROPIETARIOS_HOMBRES', 'METAS', 'ACTIVIDAD_ECONOMICA', 'INTERES_PERFIL', 'CURSO_ED_FINANCIERA', 'TIPO_EMPLAZAMIENTO', 'R_MERCANTIL', 'DIGITAL', 'INVERTIR', 'RAZON_CREAR_NEGOCIO', 'ObjectID', 'LOCALIDAD', 'UPZ', 'DIRECCION_COMPLETA', 'COMPLEMENTO', 'NOMBRE_ENCUESTADO', 'RAZON_SOCIAL', 'NOMBRE_COMERCIAL', 'TELEFONOS', 'CORREOS', 'NOMBRE_PROPIETARIO', 'NUMERO_ID_PROPIETARIO', 'TIPO_ID_NEGOCIO','NUMERO_ID_NEGOCIO']
    
    

    
